
= Neo4J Demo in Clojure

A simple demo accessing Neo4J using the `gorillalabs/neo4j-clj` library.

== Installation

This project assumes you have already installed Neo4J Desktop (Enterprise Edition). It is availble
for free for local use.  When you download the installer, be sure to copy the Activition Code and
save it.  You will need the Activation Code during the installation process.

Since the Neo4J Desktop is free to use for development, I have not played around with the
open source Docker version of Neo4J.

== Environment

The unit tests in this repo work against a locally running instance of Neo4j Desktop.  For some
unknown reason, it doesn't work right running against a basic DB in the Neo4j Aura cloud.

== Configuration after installation

Note that in the Neo4j Desktop browser, there are three (3) different entities to consider:

1. the Project
2. the DBMS
3. the DB

Keep in mind that a project can have multiple DBMS's, and a DBMS can have multiple DB's.

For our purposes, create the following configuration in Neo4j Desktop:

- Click the top-left "project" icon, then the `+ New` button to create a new project. Name it 
  "Demo Project", for example.

- In the top-right corner, click the "+ Add" button to add a "Local DBMS".  Change the default name
  to "Unit Test DBMS", if desired.  For development purposes, set the password to "secret". Then,
  click the blue "Create" button.  

- Click on the DBMS name under the Project name in the Neo4j Desktop window to highlight it, then
  click on the "Plugins" tab in the RHS panel. Select "APOC" and install to the DB.

- Click on the DBMS name under the Project name in the Neo4j Desktop window to highlight it, then
  click the green "Start" button so the DB is active (not just the neo4j desktop).  If you make any
  changes to the DB config you'll need to click the "restart" to make then take effect.

- The DBMS will create 2 DB's, "system" and "neo4j". We accept the default DB name "neo4j" in the
  DBMS.  If you click the "Details" tab on the RHS panel, you should see the Bolt protocol running
  on port 7687.

- We depend on the DB name "neo4j", the password "secret", and the port 7687 being correct. 
  These creds must be correct or the neo4j driver can't connect to the DB (it will fail auth).

=== Verify you have Java, Clojure, and Leiningen set up correctly

Try the following commands, and make sure you get similar output:

```bash
> java --version
java 13 2019-09-17
Java(TM) SE Runtime Environment (build 13+33)
Java HotSpot(TM) 64-Bit Server VM (build 13+33, mixed mode, sharing)

> lein --version
Leiningen 2.9.1 on Java 13 Java HotSpot(TM) 64-Bit Server VM
```

== Run the Unit Tests

I do this so much I have some bash aliases:

```bash
alias lct=" time (lein do clean, test)"
alias lctr="time (lein do clean, test-refresh)"
```

The first one `lct` is generic, the 2nd one `lctr` is for use with the lein-test-refresh plugin.

== Running Unit Tests - Plain

Just type

```bash
> lct   # or `lein clean ; lein test`
```

with result:

```pre
  -----------------------------------
     Clojure 1.10.3    Java 15.0.2
  -----------------------------------

  lein test tst.demo.core
  Creating session...
  Getting Neo4j version info
  Getting APOC version info
    *** APOC not installed ***

  Ran 2 tests containing 4 assertions.
  0 failures, 0 errors.
  ( lein do clean, test; )  30.19s user 0.87s system 320% cpu 9.698 total
```

The message "*** APOC not installed ***" shows that we have not installed the free APOC library of
functions for Neo4J.
We want to install APOC. The APOC library is free and very useful, so we normally want to have it available.

=== Install the APOC library

In the Neo4j Desktop window, highlight your project in the left-hand
nav pane..  Then click near the green "ACTIVE" label, which will open the "Manage" screen on the RHS of the screen.
Click on Plugins -> APOC -> Install and Restart.  After the DB has restarted, re-run the tests.

```pre
  > lct
  Java HotSpot(TM) 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
  Warning: environ value /opt/java15 for key :java-home has been overwritten with /opt/jdk-15.0.2

  lein test _bootstrap

  -----------------------------------
     Clojure 1.10.3    Java 15.0.2
  -----------------------------------

  lein test neo4j-clj.core-test
  2021-10-19T12:43:23.214312957 INFO Driver - Direct driver instance 533282421 created for server address localhost:7687
  2021-10-19T12:43:23.866709008 INFO Driver - Closing driver instance 533282421
  2021-10-19T12:43:23.871466204 INFO ConnectionPool - Closing connection pool towards localhost:7687

  lein test tst.demo.core
  2021-10-19T12:43:24.078630622 INFO Driver - Direct driver instance 1276416078 created for server address localhost:7687
  2021-10-19T12:43:24.728141941 INFO Driver - Closing driver instance 1276416078
  2021-10-19T12:43:24.728574566 INFO ConnectionPool - Closing connection pool towards localhost:7687

  lein test tst.demo.indexes
  2021-10-19T12:43:24.934835116 INFO Driver - Direct driver instance 370187245 created for server address localhost:7687
  2021-10-19T12:43:25.664557287 WARNING ChannelErrorHandler - [0xd81779d0][localhost:7687][bolt-29] Fatal error occurred in the pipeline
  2021-10-19T12:43:25.665049016 WARNING InboundMessageHandler - [0xd81779d0][localhost:7687][bolt-29] Message ignored because of the previous fatal error. Channel will be closed. Message:
  b07e
  2021-10-19T12:43:26.245530699 INFO Driver - Closing driver instance 370187245
  2021-10-19T12:43:26.245788711 INFO ConnectionPool - Closing connection pool towards localhost:7687

  lein test tst.tupelo.neo4j
  2021-10-19T12:43:26.454280398 INFO Driver - Direct driver instance 2004943989 created for server address localhost:7687
  2021-10-19T12:43:27.358833333 INFO Driver - Closing driver instance 2004943989
  2021-10-19T12:43:27.359274835 INFO ConnectionPool - Closing connection pool towards localhost:7687

  Ran 6 tests containing 57 assertions.
  0 failures, 0 errors.
  ( lein do clean, test; )  32.90s user 0.81s system 236% cpu 14.237 total
```

Notice that this time it found the APOC library.

== Code Structure

All interesting code is in the NS `tst.demo.core`, under the `test` directory.  I like this naming structure better then
the `-test` suffix as it doesn't mess with the filename, and there is no conflict between hyphens "core-test"
vs underscores "core_test.clj".

== Keeping Dependency Versions Up-To-Date

This project includes the `lein-ancient` plugin, which will tell you if any of your dependency
libraries are out of date. I have an alias:

```bash
alias laca="lein ancient check :all"
```

which will give you a list of version updates you should make, or just

```pre
all artifacts are up-to-date.
```

if you are already up-to-date on everything.

== License

Copyright © 2021  Alan Thompson

Distributed under the link:https://www.eclipse.org/legal/epl-v10.html[Eclipse Public License], the same as Clojure.

